name: Minimal Workflow Test

on:
  push:
    branches:
      - main # 실제 푸시하는 브랜치 이름으로 설정 (예: master)

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "드디어 워크플로우가 실행됩니다!"