# .github/workflows/docs_automation.yml
name: Generate README with AI

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행

permissions:
  contents: write # README 파일을 수정하고 커밋하기 위해 필수

jobs:
  build-and-update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: 4. Install Python dependencies
        run: pip install google-generativeai lxml

      - name: 5. Generate Doxygen XML
        run: doxygen Doxyfile

      - name: 6. Run AI conversion script
        env:
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python convert_docs.py

      - name: 7. Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: ✨ README.md 자동 업데이트'
          file_pattern: 'README.md'